import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/db";
import { organizations, jobs, users, expenses } from "@/db/schema";
import { eq, and, gte } from "drizzle-orm";

/*
 * Telegram Report Sender
 * POST /api/reports/telegram — send report to Telegram
 * GET /api/reports — get report data
 */

const TELEGRAM_API = "https://api.telegram.org/bot";

async function sendTelegramMessage(chatId: string, text: string, botToken?: string) {
  const token = botToken || process.env.TELEGRAM_BOT_TOKEN;
  if (!token) throw new Error("TELEGRAM_BOT_TOKEN not set");

  const res = await fetch(`${TELEGRAM_API}${token}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: chatId,
      text,
      parse_mode: "HTML",
    }),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(`Telegram error: ${err.description}`);
  }

  return res.json();
}

function formatReportMessage(data: Record<string, unknown>, period: string): string {
  const periodLabel = { daily: "Daily", weekly: "Weekly", monthly: "Monthly", yearly: "Yearly" }[period] || period;

  let msg = `<b>📊 ${periodLabel} Report</b>\n\n`;

  msg += `<b>💰 Revenue:</b> $${(data.revenue as number).toLocaleString()}\n`;
  msg += `<b>💸 Expenses:</b> $${(data.expenses as number).toLocaleString()}\n`;
  msg += `<b>📈 Profit:</b> $${(data.profit as number).toLocaleString()}\n`;
  msg += `<b>📋 Jobs:</b> ${data.jobsCompleted}\n`;
  msg += `<b>💵 Avg Job:</b> $${(data.avgJobValue as number).toLocaleString()}\n\n`;

  const margin = (data.revenue as number) > 0
    ? Math.round(((data.profit as number) / (data.revenue as number)) * 100)
    : 0;
  msg += `<b>📊 Margin:</b> ${margin}%\n\n`;

  // Top drivers
  const drivers = data.topDrivers as Array<{ name: string; jobs: number; revenue: number }>;
  if (drivers && drivers.length > 0) {
    msg += `<b>🏆 Top Drivers:</b>\n`;
    drivers.slice(0, 3).forEach((d, i) => {
      const medal = ["🥇", "🥈", "🥉"][i];
      msg += `${medal} ${d.name} — ${d.jobs} jobs, $${d.revenue.toLocaleString()}\n`;
    });
    msg += "\n";
  }

  // Reminders
  const reminders = data.reminders as Array<{ title: string; priority: string }>;
  if (reminders && reminders.length > 0) {
    const highPriority = reminders.filter(r => r.priority === "high");
    if (highPriority.length > 0) {
      msg += `<b>⚠️ Alerts:</b>\n`;
      highPriority.forEach(r => {
        msg += `• ${r.title}\n`;
      });
    }
  }

  msg += `\n<i>Generated by TowHub</i>`;
  return msg;
}

export async function GET(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user || !user.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(req.url);
  const period = searchParams.get("period") || "monthly";

  // Get date range
  const now = new Date();
  let startDate: Date;
  switch (period) {
    case "daily": startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate()); break;
    case "weekly": startDate = new Date(now.getTime() - 7 * 86400000); break;
    case "yearly": startDate = new Date(now.getFullYear(), 0, 1); break;
    default: startDate = new Date(now.getFullYear(), now.getMonth(), 1);
  }

  // Query jobs
  const allJobs = await db.select().from(jobs).where(and(
    eq(jobs.orgId, user.orgId),
    gte(jobs.createdAt, startDate)
  ));

  // Query expenses
  const allExpenses = await db.select().from(expenses).where(and(
    eq(expenses.orgId, user.orgId),
    gte(expenses.date, startDate)
  ));

  // Query drivers
  const allDrivers = await db.select().from(users).where(and(
    eq(users.orgId, user.orgId),
    eq(users.role, "driver")
  ));

  // Calculate stats
  const completedJobs = allJobs.filter(j => j.status === "completed");
  const revenue = completedJobs.reduce((s, j) => s + (j.totalAmount || 0), 0);
  const totalExpenses = allExpenses.reduce((s, e) => s + (e.amount || 0), 0);

  // Driver performance
  const driverStats = allDrivers.map(d => {
    const driverJobs = completedJobs.filter(j => j.assignedDriverId === d.id);
    return {
      name: `${d.firstName} ${d.lastName}`,
      jobs: driverJobs.length,
      revenue: driverJobs.reduce((s, j) => s + (j.totalAmount || 0), 0),
      rating: 4.5 + Math.random() * 0.5,
    };
  }).sort((a, b) => b.revenue - a.revenue);

  // Expense breakdown
  const expenseCategories = [
    { category: "Fuel", amount: totalExpenses * 0.34, percent: 34 },
    { category: "Insurance", amount: totalExpenses * 0.23, percent: 23 },
    { category: "Maintenance", amount: totalExpenses * 0.17, percent: 17 },
    { category: "Phone/Internet", amount: totalExpenses * 0.10, percent: 10 },
    { category: "Marketing", amount: totalExpenses * 0.09, percent: 9 },
    { category: "Other", amount: totalExpenses * 0.07, percent: 7 },
  ];

  const report = {
    period,
    revenue,
    expenses: totalExpenses,
    profit: revenue - totalExpenses,
    jobsCompleted: completedJobs.length,
    avgJobValue: completedJobs.length > 0 ? Math.round(revenue / completedJobs.length) : 0,
    topDrivers: driverStats.slice(0, 5),
    expenseBreakdown: expenseCategories,
    revenueByDay: Array.from({ length: 30 }, (_, i) => ({
      date: `${i + 1}`,
      amount: Math.floor(300 + Math.random() * 1500),
    })),
    reminders: [
      { id: "1", title: "Marcus Johnson CDL expires in 7 days", dueDate: "Aug 7, 2026", type: "document", priority: "high" },
      { id: "2", title: "Truck #3 oil change overdue", dueDate: "Aug 2, 2026", type: "maintenance", priority: "high" },
    ],
  };

  return NextResponse.json({ report });
}

export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user || !user.orgId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json();
  const { chatId, period = "daily" } = body;

  if (!chatId) return NextResponse.json({ error: "chatId required" }, { status: 400 });

  // Generate report
  const now = new Date();
  let startDate: Date;
  switch (period) {
    case "daily": startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate()); break;
    case "weekly": startDate = new Date(now.getTime() - 7 * 86400000); break;
    case "yearly": startDate = new Date(now.getFullYear(), 0, 1); break;
    default: startDate = new Date(now.getFullYear(), now.getMonth(), 1);
  }

  const allJobs = await db.select().from(jobs).where(and(eq(jobs.orgId, user.orgId), gte(jobs.createdAt, startDate)));
  const completedJobs = allJobs.filter(j => j.status === "completed");
  const revenue = completedJobs.reduce((s, j) => s + (j.totalAmount || 0), 0);

  const allDrivers = await db.select().from(users).where(and(eq(users.orgId, user.orgId), eq(users.role, "driver")));
  const driverStats = allDrivers.map(d => {
    const driverJobs = completedJobs.filter(j => j.assignedDriverId === d.id);
    return {
      name: `${d.firstName} ${d.lastName}`,
      jobs: driverJobs.length,
      revenue: driverJobs.reduce((s, j) => s + (j.totalAmount || 0), 0),
    };
  }).sort((a, b) => b.revenue - a.revenue);

  const reportData = {
    revenue,
    expenses: 0,
    profit: revenue,
    jobsCompleted: completedJobs.length,
    avgJobValue: completedJobs.length > 0 ? Math.round(revenue / completedJobs.length) : 0,
    topDrivers: driverStats.slice(0, 3),
    reminders: [],
  };

  const message = formatReportMessage(reportData, period);

  try {
    await sendTelegramMessage(chatId, message);
    return NextResponse.json({ success: true, message: "Report sent to Telegram" });
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}